# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
env:
  - _R_CHECK_FORCE_SUGGESTS_=false # because of Rmpi, ncdf4, hydromat, and weathergen
sudo: false
cache: packages
warnings_are_errors: false # turn this back on for more severe testing

# Next three settings (latex, r_build_args, and r_check_args -- though, the latter two
# are not used because we use our own 'script' section: see there): because unit tests
# take now too much time due to the extended unit test project; some travis runs fail
# due to taking longer than the allotted 60-min maximum; for now omit PDF vignettes and
# manual until we have proper, fast running unit tests
latex: false
r_build_args: '--no-build-vignettes --no-manual'
r_check_args: '--ignore-vignettes --no-manual'
r_packages: hunspell

addons:
  apt:
    packages:
    - libproj-dev
    - libgeos-dev
    - libgdal-dev
    - libnetcdf-dev

before_install:
  # pwd = <repo>/<repo-name>, here DrylandEcology/rSFSW2
  # Install dependencies of rSOILWAT2 (because rSOILWAT2 is installed 'before install'
  # and thus dependencies are not installed and r_packages has not taken effect yet)
  - Rscript -e 'pkgs <- setdiff(c("blob", "DBI", "RSQLite"), installed.packages()); if (length(pkgs) > 0) utils::install.packages(pkgs)'
  # Obtain source code of rSOILWAT2 from github and save at DrylandEcology/rSOILWAT2
  - git clone -b master --single-branch --recursive https://github.com/DrylandEcology/rSOILWAT2.git ../rSOILWAT2
  # Install rSOILWAT2 without help pages and without vignettes
  - R CMD INSTALL --no-docs --no-help ../rSOILWAT2


script:
  - R CMD build --no-build-vignettes --no-manual .
  # The extended unit test project (commit db3948e6aa746d012dbc4f25b0e9bb2a4186305f)
  # takes about 16 min which is too long for the default settings of 10-min and times out
  # On failure, display file 'testthat.Rout.fail' for more information and fail
  - travis_wait 30 R CMD check *tar.gz --as-cran --ignore-vignettes --no-manual || { cat rSFSW2.Rcheck/tests/testthat.Rout* && 1; }

after_success:
  - travis_wait 30 Rscript -e 'covr::codecov()'
